#############
### base ###
#############
FROM python:3.9-slim-buster

LABEL \
    org.opencontainers.image.title="BioSimulators-base" \
    org.opencontainers.image.description="Docker image the dependencies for the simulation tools registered BioSimulators" \
    org.opencontainers.image.url="https://biosimulators.org/" \
    org.opencontainers.image.documentation="https://docs.biosimulations.org/" \
    org.opencontainers.image.source="https://github.com/biosimulators/Biosimulators" \
    org.opencontainers.image.authors="BioSimulators Team <info@biosimulators.org>" \
    org.opencontainers.image.vendor="BioSimulators Team"

