name: Bug
description: Report a bug to help us improve
title: "🐛: "
labels: 
  - "bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "What is the bug?"
      description: "Please provide a clear and concise description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: When does the bug occur?
      description: Please describe how the bug can be reproduced
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: preferred-behavior
    attributes:
      label: How should BioSimulators have behaved?
      description: Please describe what you expected to happen
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please attach any screenshots that illustrate the bug
    validations:
      required: false

  - type: dropdown
    id: device
    attribute:
      label: Which types of devices does the bug occur in?
      multiple: true
      options:
        - Desktop
        - Tablet
        - Phone
        - Other
    validations:
      required: false
