name: Start a discussion
description: Initiate a discussion among the community
title: ""
labels:
  - discussion
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: "What would you like to discuss?"
      description: "Please describe the issue that you would like to discuss with the community."
    validations:
      required: true
