name: Question
description: Ask a question to get information about BioSimulators
title: '[Question]: '
labels: 
  - question
assignees: []
body: 
  - type: textarea
    id: description
    attributes:
      label: "What is your question?"
      description: "Please describe your question."
    validations:
      required: true
