name: Feature
description: Suggest an idea for BioSimulators
title: '[Feature request]:'
labels:
  - enhancement
assignees: []
body:
  - type: textarea
    id: feature
    attributes:
      label: "What feature would you like BioSimulators to have?"
      description: "Please provide a clear and concise description of the desired feature."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "What alternatives have you considered?"
      description: "Please provide a clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please provide a clear and concise description of what the problem is."
      placeholder: I'm always frustrated when ...
    validations:
      required: false
