name: Validate or contribute a simulator
description: Validate or contribute a containerized simulation tool, another version of the tool, or update a version of the tool.
title: "[Simulation capabilities]: "
labels: 
  - "Validate/submit simulator"
assignees: []
body:
  - type: textarea
    id: tool
    attributes:
      label: "Simulation tool"
      description: "Please follow the YAML template below to indicate the id, version, and URL of the specifications of the simulation tool and whether you would like to submit the tool to the BioSimulators registry or just validate it"
      value: |
        ---
        id: tellurium
        version: 2.1.6
        specificationsUrl: https://raw.githubusercontent.com/biosimulators/Biosimulators_tellurium/2.1.6/biosimulators.json
        validateImage: true
        commitSimulator: true

        ---
    validations:
      required: false

  - type: checkboxes
    id: compliance
    attributes:
      label: Support for BioSimulators' conventions
      description: |
        Please use this checklist to confirm your simulation tool is ready for submission to BioSimulators.

        Instructions for creating simulation tools and examples are available at https://docs.biosimulations.org/users/creating-tools/.
      options:
        - label: The simulation tool is provided as a Docker image
          required: true
        - label: The `ENTRYPOINT` of the image is a [BioSimulators-compliant command-line interface](https://docs.biosimulations.org/concepts/conventions/simulator-interfaces/) 
          required: true
        - label: This command-line interface supports the [COMBINE/OMEX archive](https://combinearchive.org/) format
          required: true
        - label: This command-line interface supports the [Simulation Experiment Description Markup Language (SED-ML)](https://combinearchive.org/) format
          required: true
        - label: This command-line interface supports the [Hierarchical Data Format (HDF5)](https://www.hdfgroup.org/solutions/hdf5/)
          required: true
        - label: The capabilities of the tool are described using [BioSimulators' format](https://docs.biosimulations.org/concepts/conventions/simulator-capabilities/)
          required: true
        - label: The modeling frameworks supported by the tool are described using [Systems Biology Ontology (SBO)](https://github.com/EBI-BioModels/SBO/issues) terms
          required: true
        - label: The algorithms supported by the tool are described using [Kinetic Simulation Algorithm Ontology (KiSAO)](https://github.com/SED-ML/KiSAO/issues/new/choose) ontology terms
          required: true
        - label: The model formats supported by the tool are described using [EMBRACE Data and Methods (EDAM)](https://github.com/edamontology/edamontology/issues/new/choose) ontology terms
          required: true
        - label: The licenses supported by the tool are described using [Software Package Data Exchange (SPDX)](https://tools.spdx.org/app/submit_new_license/) identifiers
          required: true
        - label: The source code for the simulation tool is publicly available
          required: false
        - label: The simulation tool is available through a software repository such as CRAN or PyPI
          required: false
        - label: The simulation tool is registered with [bio.tools](https://bio.tools/)
          required: false
        - label: The Docker image provides [Open Containers Initiative-compliant metadata](https://docs.biosimulations.org/concepts/conventions/simulator-images/)
          required: false
        - label: The Docker image provides [BioContainers-compliant metadata](https://docs.biosimulations.org/concepts/conventions/simulator-images/)
          required: false
        - label: The Docker image is registered with [BioContainers](https://biocontainers.pro/)
          required: false

  - type: markdown
    attributes:
      value: |
        ### Post-submission approval workflow

        Once you submit this issue, BioSimulators will use the following workflow to validate, approve, and optionally commit your simulator to the BioSimulators database:

        1. An issue will be created with the label `Validate/submit simulator`.
        2. An automated action will review your submission:
           1. Retrieve the specifications of your simulator.
           2. Validate these specifications.
           3. Check if you have permissions to submit this simulator.
              - If no simulator has been submitted with this id, a GitHub team will be created to manage permissions to edited the specifications of your simulator and you will be added as a maintainer of this team. This will enable you to add collaborators to this team at https://github.com/orgs/biosimulators/teams/simulator-developers/teams.
              - If your simulator is already in the BioSimulators registry, the action will check that you are member of the team which owns that simulator. If you are not a member, you will not be allowed to edit the specifications of the simulator. In that case, you will need to request membership to the team for your simulator.
           4. Optionally, validate the containerized simulator specified in your specifications.
        3. If the validation fails, any errors will be posted to this issue. After fixing these issues, please edit the first block of this issue to re-initiate the automated validation.
        4. If the validation succeeds, the `Validated` label will be added to the issue.
        5. The submission of the first version of your simulator will be reviewed by the BioSimulators Team.
           1. If there are any concerns about your submission, the BioSimulators Team will use this issue to communicate them to you.
           2. The BioSimulators Team will work with you to resolve these concerns.
        6. Once your simulator is approved, the BioSimulators Team will add the label `Approved` to this issue. 
        7. If requested, the simulator will automatically be committed to the BioSimulators database and the issue will automatically be closed.

  - type: markdown
    attributes:
      value: |
        ### Re-submission change list

        If you need to revise your simulator to pass the validation, please use this section to briefly describe the changes that you made.
