name: Validate or contribute a simulator
description: Validate or contribute a containerized simulation tool, another version of the tool, or update a version of the tool.
title: "[Simulation capabilities]: "
labels: 
  - "Validate/submit simulator"
assignees: []
body:
  - type: markdown
    value: |
      ## Instructions

      Please use this form to validate or contribute a simulation tool, another version of the tool, or update a version of the tool.

      Instructions for creating simulation tools and examples are available at https://biosimulators.org/help.
