name: Commit simulator

on:
  issues:
    types: [closed]

jobs:
  integrate:
    name: Commit
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'Submit simulator') }}
    steps:
    - name: Install processing utilities
      run: |
        sudo apt-get install -y --no-install-recommends git python3 python3-pip
        pip3 install -U setuptools
        pip3 install git+https://github.com/biosimulations/Biosimulations_utils.git@align-with-api#egg=Biosimulations_utils[ci-actions]
    - name: Commit submission
      env:
        ISSUE_NUMBER: github.event.issue.number
      run: |
        python3 - <<-EOF
          from Biosimulations_utils.ci_actions.validate_commit_simulator import ValidateCommitSimulatorCiActions
          ValidateCommitSimulatorCiActions().commit()
        EOF
