name: Commit simulator

on:
  issues:
    types: [labeled]

jobs:
  integrate:
    name: Commit
    runs-on: ubuntu-latest
    if: |
        ${{
            contains(github.event.issue.labels.*.name, 'Submit simulator')
            && contains(github.event.issue.labels.*.name, 'Validated')
            && !contains(github.event.issue.labels.*.name, 'Action error')
            && contains(github.event.issue.labels.*.name, 'Approved')
        }}
    steps:
      - name: Checkout Biosimulations_utils
        uses: actions/checkout@v2
        with:
          repository: biosimulations/Biosimulations_utils
          ref: align-with-api

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('${GITHUB_WORKSPACE}/requirements.txt') }}-${{ hashFiles('${GITHUB_WORKSPACE}/requirements.optional.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      - name: Install simulator validation utilities
        run: |
          cd ${GITHUB_WORKSPACE}
          python -m pip install .[ci-actions]

      - name: Commit submission
        env:
          GH_REPO: ${{ github.repository }}
          GH_ACTION_RUN_ID: ${{ github.run_id }}
          GH_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_ISSUES_USER: ${{ secrets.GH_ISSUES_USER }}
          GH_ISSUES_ACCESS_TOKEN: ${{ secrets.GH_ISSUES_ACCESS_TOKEN }}
        shell: python
        run: |
          from Biosimulations_utils.ci_actions.validate_commit_simulator import CommitSimulatorAction
          ValidateSimulatorAction().run()
