name: Commit simulator

on:
  issues:
    types: [labeled]

jobs:
  integrate:
    name: Commit
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'Submit simulator') && contains(github.event.issue.labels.*.name, 'Validated') && contains(github.event.issue.labels.*.name, 'Approved') }}
    steps:
    - name: Install processing utilities
      run: |
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get install -y --no-install-recommends git python3.7 python3 python3-pip
        python3.7 -m pip install pip
        python3.7 -m pip install setuptools
        python3.7 -m pip install git+https://github.com/biosimulations/Biosimulations_utils.git@align-with-api#egg=Biosimulations_utils[ci-actions]
    - name: Commit submission
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_ISSUES_USER: ${{ secrets.GH_ISSUES_USER }}
        GH_ISSUES_ACCESS_TOKEN: ${{ secrets.GH_ISSUES_ACCESS_TOKEN }}
      run: |
        python3.7 - <<-EOF
        from Biosimulations_utils.ci_actions.validate_commit_simulator import ValidateCommitSimulatorCiActions
        ValidateCommitSimulatorCiActions().commit()
        EOF
