name: Validate simulator

on:
  issues:
    types: [opened, edited]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'Submit simulator') }}
    steps:
    - name: Install Python 3.7 and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get install -y --no-install-recommends \
            git \
            python3.7 \
            python3 \
            python3-pip
        python3.7 -m pip install pip
        python3.7 -m pip install setuptools
    - name: Install Docker
      run: |
        docker --help

        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) \
           stable"
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io
    - name: Install simulator validation utilities
      run: python3.7 -m pip install git+https://github.com/biosimulations/Biosimulations_utils.git@align-with-api#egg=Biosimulations_utils[ci-actions,docker]
    - name: Process submission
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_ISSUES_USER: ${{ secrets.GH_ISSUES_USER }}
        GH_ISSUES_ACCESS_TOKEN: ${{ secrets.GH_ISSUES_ACCESS_TOKEN }}
      run: |
        python3.7 - <<-EOF
        from Biosimulations_utils.ci_actions.validate_commit_simulator import ValidateCommitSimulatorCiActions
        ValidateCommitSimulatorCiActions().validate()
        EOF
