name: Validate simulator

on:
  issues:
    types: [opened, edited]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'Submit simulator') }}
    steps:
    - name: Install processing utilities
      run: |
        sudo apt-get install -y --no-install-recommends software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get install -y --no-install-recommends git python3.7 python3.7-pip
        pip3.7 install -U setuptools
        pip3.7 install git+https://github.com/biosimulations/Biosimulations_utils.git@align-with-api#egg=Biosimulations_utils[ci-actions]
    - name: Process submission
      env:
        ISSUE_NUMBER: github.event.issue.number
      run: |
        python3.7 - <<-EOF
          from Biosimulations_utils.ci_actions.validate_commit_simulator import ValidateCommitSimulatorCiActions
          ValidateCommitSimulatorCiActions().validate()
        EOF
